#!/bin/bash
# Rocky port of setup_slurm.sh
#
# Changes from the Ubuntu original:
#   apt-get install slurmctld slurm-client → dnf install of locally built RPMs
#     (see build_slurm_rpms.sh — Slurm is not packaged for Rocky)
#     controller: slurm + slurm-slurmctld
#     nodes:      slurm + slurm-slurmd
#   --reload flag renamed internally from SKIP_APT to SKIP_INSTALL (same
#     behaviour, still accepts --reload)
#   firewalld rules added — slurmctld 6817, slurmd 6818, slurmdbd 6819.
#     Without these, nodes show as DOWN with "Not responding" and the cause is
#     not obvious. Ubuntu's ufw was inactive so the original never needed it.
#   /var/run → /run for pid files; Rocky clears /var/run on boot via tmpfiles,
#     and the slurm.conf generated by generate_slurm_conf.sh now matches.
#   Log/spool dirs get an explicit tmpfiles rule so they survive reboot.

set -uo pipefail

USER="hpcadmin"
CLUSTER_FILE="cluster.txt"
PASS_FILE="PASSWORD.txt"

CONTROLLER="haydeanlogin"
SLURM_CONF="slurm.conf"
RPM_SHARE="/home/hpcadmin/slurm-rpms"

export SSHPASS="$(tr -d '\r\n' < "$PASS_FILE")"
SSH_OPTS="-o StrictHostKeyChecking=no -o ConnectTimeout=10"

# ── Args ──────────────────────────────────────────────────────────────────────
SKIP_INSTALL=false
for arg in "$@"; do
  [[ "$arg" == "--reload" ]] && SKIP_INSTALL=true
done

if $SKIP_INSTALL; then
  echo "== Mode: RELOAD (skipping package installs) =="
else
  echo "== Mode: FULL INSTALL =="
  if [[ ! -d "$RPM_SHARE" ]]; then
    echo "ERROR: $RPM_SHARE not found — run ./build_slurm_rpms.sh first"
    exit 1
  fi
fi

echo "== Loading cluster =="
mapfile -t nodes < <(tr -d '\r' < "$CLUSTER_FILE")
echo "Nodes:"; printf "  %s\n" "${nodes[@]}"

# ── Step 1: Controller ────────────────────────────────────────────────────────
echo ""
echo "== Step 1: Setup slurmctld on controller =="

if ! $SKIP_INSTALL; then
  sudo dnf install -y \
    "$RPM_SHARE"/slurm-[0-9]*.rpm \
    "$RPM_SHARE"/slurm-slurmctld-*.rpm \
    "$RPM_SHARE"/slurm-perlapi-*.rpm \
    "$RPM_SHARE"/slurm-contribs-*.rpm
fi

sudo mkdir -p /etc/slurm /var/spool/slurmctld /var/log/slurm
sudo cp "$SLURM_CONF" /etc/slurm/slurm.conf
sudo chown slurm:slurm /etc/slurm/slurm.conf
sudo chown -R slurm:slurm /var/spool/slurmctld /var/log/slurm

# Rocky clears /run on boot — recreate the pid dir every boot.
echo 'd /run/slurm 0755 slurm slurm -' | sudo tee /etc/tmpfiles.d/slurm.conf > /dev/null
sudo systemd-tmpfiles --create /etc/tmpfiles.d/slurm.conf

if systemctl is-active --quiet firewalld; then
  sudo firewall-cmd --permanent --add-port=6817/tcp   # slurmctld
  sudo firewall-cmd --permanent --add-port=6819/tcp   # slurmdbd
  sudo firewall-cmd --reload
  echo "  opened slurmctld/slurmdbd ports in firewalld"
fi

sudo systemctl enable slurmctld
sudo systemctl restart slurmctld

# Wait for slurmctld to come up before pushing to nodes
echo "  Waiting for slurmctld..."
for i in {1..10}; do
  sudo systemctl is-active --quiet slurmctld && echo "  slurmctld is up" && break
  [[ $i -eq 10 ]] && echo "  WARNING: slurmctld did not start in time" && sudo journalctl -u slurmctld -n 20 --no-pager
  sleep 2
done

# ── Step 2: Nodes (parallel) ──────────────────────────────────────────────────
echo ""
echo "== Step 2: Setup slurmd on nodes (parallel) =="

pids=()
declare -A pid_to_host

for host in "${nodes[@]}"; do
  host="${host//$'\r'/}"
  [ -z "$host" ] && continue

  (
    if ! $SKIP_INSTALL; then
      echo "[$host] installing packages"
      # RPMs come from shared /home, so no scp of packages is needed.
      sshpass -e ssh $SSH_OPTS "$USER@$host" "
        sudo -n dnf install -y \
          $RPM_SHARE/slurm-[0-9]*.rpm \
          $RPM_SHARE/slurm-slurmd-*.rpm
      " || { echo "FAILED install: $host"; exit 1; }
    fi

    echo "[$host] copying config"
    sshpass -e scp $SSH_OPTS "$SLURM_CONF" "$USER@$host:/tmp/slurm.conf" \
      || { echo "FAILED scp: $host"; exit 1; }

    echo "[$host] configuring and restarting slurmd"
    sshpass -e ssh $SSH_OPTS "$USER@$host" "
      sudo -n mkdir -p /etc/slurm /var/spool/slurmd /var/log/slurm
      sudo -n mv /tmp/slurm.conf /etc/slurm/slurm.conf
      sudo -n chown slurm:slurm /etc/slurm/slurm.conf
      sudo -n chown -R slurm:slurm /var/spool/slurmd /var/log/slurm

      echo 'd /run/slurm 0755 slurm slurm -' | sudo -n tee /etc/tmpfiles.d/slurm.conf > /dev/null
      sudo -n systemd-tmpfiles --create /etc/tmpfiles.d/slurm.conf

      if systemctl is-active --quiet firewalld; then
        sudo -n firewall-cmd --permanent --add-port=6818/tcp
        sudo -n firewall-cmd --reload
      fi

      sudo -n systemctl enable slurmd
      sudo -n systemctl restart slurmd
    " || { echo "FAILED config: $host"; exit 1; }

    echo "[$host] DONE"
  ) &

  pid=$!
  pids+=($pid)
  pid_to_host[$pid]="$host"
done

# Collect results
FAILED=()
for pid in "${pids[@]}"; do
  wait "$pid" || FAILED+=("${pid_to_host[$pid]}")
done

if [[ ${#FAILED[@]} -gt 0 ]]; then
  echo "  FAILED nodes: ${FAILED[*]}"
else
  echo "  All nodes configured successfully"
fi

echo "== Step 2 COMPLETE =="

# ── Step 3: Verify ────────────────────────────────────────────────────────────
echo ""
echo "== Step 3: Verify =="
echo "--- sinfo ---"
sinfo 2>/dev/null || echo "sinfo failed — slurmctld may still be starting"
echo "--- node states ---"
scontrol show nodes 2>/dev/null | grep -E "NodeName|State|CPUTot|Reason"

if [[ ${#FAILED[@]} -gt 0 ]]; then
  echo ""
  echo "Some nodes failed. To debug a node:"
  echo "  ssh hpcadmin@haydean1.local 'sudo journalctl -u slurmd -n 30 --no-pager'"
  echo "If nodes show DOWN 'Not responding', check firewalld on the node:"
  echo "  ssh hpcadmin@haydean1.local 'sudo firewall-cmd --list-all'"
  exit 1
fi
